# Matrices

- [Définition d'arrays à partir de listes](#définition-darrays-à-partir-de-listes)
- [Définition de matrices 2D à partir de listes](#définition-de-matrices-2d-à-partir-de-listes)

In [2]:
import numpy as np

## Définition d'arrays à partir de listes

In [3]:
L = [ 4, 5, 8, 2, 1, 5, 1 ]
tab = np.array(L)



In [4]:
print (L)
print (tab)
print (tab.shape)

[4, 5, 8, 2, 1, 5, 1]
[4 5 8 2 1 5 1]
(7,)


In [5]:
print(tab[2:5])

[8 2 1]


In [6]:
print (tab.dtype) # type des éléments contenus

int64


In [7]:
x = np .arange(0, 2.1, 0.1)

print(x)
print(type(x))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]
<class 'numpy.ndarray'>


In [8]:
y = np.linspace(0, 1, 100)
print(y)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [9]:
v = np.arange(1, 10, 2)
w = v - 3
print(v)
print(w)

print (v * w) # produit terme à terme


[1 3 5 7 9]
[-2  0  2  4  6]
[-2  0 10 28 54]


In [10]:
v = np.array([0, 1, 2])
w = np.array([7, 5, 8])
print (dot(v, w))
print(cross(v, w))


NameError: name 'dot' is not defined

In [ ]:
M = np.array([1, 2, 4, 5, 9, 7])
M.shape = (3,2)

print(M)
print(M.T)

In [ ]:
P = np.array([7, 2, 46, 5, 9, 7])
P.shape=(2, 3)

print(M @ P)


## Définition de matrices 2D à partir de listes

In [12]:
L2 = [[1, 2, 3,], [4, 5, 8], [7, 5, 3]]

M2 = np.array(L2)

A = np.array([[4, 8, 9, 7, 5],
              [5, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])
B = np.array([[7, 8, 9, 7, 5],
              [852, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])
print(A)

[[4 8 9 7 5]
 [5 8 6 7 1]
 [7 8 9 6 7]]


In [11]:
print(A[1:2, 3:4])

NameError: name 'A' is not defined

## Opérations sur les matrices

### Opérations terme-à-terme

In [14]:
A = np.array([[4, 8, 9, 7, 5],
              [5, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])
B = np.array([[7, 8, 9, 7, 5],
              [852, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])

print(A + B)
print(A * B)
print(A - B)
print(A / B)

print(A @ B.T)


[[ 11  16  18  14  10]
 [857  16  12  14   2]
 [ 14  16  18  12  14]]
[[  28   64   81   49   25]
 [4260   64   36   49    1]
 [  49   64   81   36   49]]
[[  -3    0    0    0    0]
 [-847    0    0    0    0]
 [   0    0    0    0    0]]
[[0.57142857 1.         1.         1.         1.        ]
 [0.00586854 1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]]
[[ 247 3580  250]
 [ 207 4410  202]
 [ 271 6131  279]]
