# Matrices

- [Définition d'arrays à partir de listes](#définition-darrays-à-partir-de-listes)
- [Définition de matrices 2D à partir de listes](#définition-de-matrices-2d-à-partir-de-listes)

In [ ]:
import numpy as np

## Définition d'arrays à partir de listes

In [ ]:
L = [ 4, 5, 8, 2, 1, 5, 1 ]
tab = np.array(L)



In [ ]:
print (L)
print (tab)
print (tab.shape)

In [ ]:
print(tab[2:5])

In [ ]:
print (tab.dtype) # type des éléments contenus

In [ ]:
x = np .arange(0, 2.1, 0.1)

print(x)
print(type(x))

In [ ]:
y = np.linspace(0, 1, 100)
print(y)

In [ ]:
v = np.arange(1, 10, 2)
w = v - 3
print(v)
print(w)

print (v * w) # produit terme à terme


In [ ]:
v = np.array([0, 1, 2])
w = np.array([7, 5, 8])
print (dot(v, w))
print(cross(v, w))


In [ ]:
M = np.array([1, 2, 4, 5, 9, 7])
M.shape = (3,2)

print(M)
print(M.T)

In [ ]:
P = np.array([7, 2, 46, 5, 9, 7])
P.shape=(2, 3)

print(M @ P)


## Définition de matrices 2D à partir de listes

In [18]:
L2 = [[1, 2, 3,], [4, 5, 8], [7, 5, 3]]

M2 = np.array(L2)

A = np.array([[4, 8, 9, 7, 5],
              [5, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])
B = np.array([[7, 8, 9, 7, 5],
              [852, 8, 6, 7 ,1],
              [7, 8, 9, 6, 7]])
print(A)

[[4 8 9 7 5]
 [5 8 6 7 1]
 [7 8 9 6 7]]


In [19]:
print(A[1:2, 3:4])

[[7]]


## Opérations sur les matrices

### Opérations terme-à-terme

In [20]:
print(A + M2)

ValueError: operands could not be broadcast together with shapes (3,5) (3,3) 