# Matrices

- [Définition d'arrays à partir de listes](#définition-darrays-à-partir-de-listes)
- [Définition de matrices 2D à partir de listes](#définition-de-matrices-2d-à-partir-de-listes)

In [ ]:
import numpy as np

## Définition d'arrays à partir de listes

In [ ]:
L = [ 4, 5, 8, 2, 1, 5, 1 ]
tab = np.array(L)



In [ ]:
print (L)
print (tab)
print (tab.shape)

In [ ]:
print(tab[2:5])

In [ ]:
print (tab.dtype) # type des éléments contenus

In [ ]:
x = np .arange(0, 2.1, 0.1)

print(x)
print(type(x))

In [ ]:
y = np.linspace(0, 1, 100)
print(y)

In [ ]:
v = np.arange(1, 10, 2)
w = v - 3
print(v)
print(w)

print (v * w) # produit terme à terme


In [43]:
v = np.array([0, 1, 2])
w = np.array([7, 5, 8])
print (dot(v, w))
print(cross(v, w))


21
[-2 14 -7]


In [40]:
M = np.array([1, 2, 4, 5, 9, 7])
M.shape = (3,2)

print(M)
print(M.T)

[[1 2]
 [4 5]
 [9 7]]
[[1 4 9]
 [2 5 7]]


In [44]:
P = np.array([7, 2, 46, 5, 9, 7])
P.shape=(2, 3)

print(M @ P)


[[ 17  20  60]
 [ 53  53 219]
 [ 98  81 463]]
21


## Définition de matrices 2D à partir de listes

In [55]:
L2 = [[1, 2, 3,], [4, 5, 8], [7, 5, 3]]
M2 = np.array(L2)

print(M2)
print(np.linalg.norm(M2))

[[1 2 3]
 [4 5 8]
 [7 5 3]]
14.212670403551895
